---
title: "ReadingAllTables"
author: "Rebecca Silva"
date: "July 25, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(mosiac)
```

```{r}
# Defining Vars

Year = c(1971:2019)
Sex = c("M", "W")
AgeGp = c("18-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80-84", "85-89", "90-94", "95-99", "100-104")
AgeGpID = c(1:17)

#Functions

findURL <- function( path){
  sprintf(path, a)
}


#remove everything after stlye of stroke bc in title 
tidyHeader <- function(x){
  if( grepl("SCY", x, fixed = T)){
    x <- gsub("SCY.*", "", x)
  }
  else {
    x <- gsub("LCM.*", "", x)
  }
  x <- gsub(" ", "", x)
}

# test if table exists  on page
testDNExists <- function(web){  
  text <- web%>% 
    html_nodes("p") %>% 
    html_text()
  binary <- grepl("No Top 10 data", text, fixed = T)
  if (any(binary == TRUE)){
    return(TRUE)
  } 
  else{ return (FALSE)}
}
```


##1 year (Age ages)
```{r}
## 1 year  - so will have men all ages year 2019 
tbls_AllAge <- list()
for (i in AgeGpID) {
  path <- sprintf("https://www.usms.org/comp/tt/toptenlist.php?CourseID=1&Year=2019&Sex=M&AgeGroupID=%d", i )
  web <- read_html(path)
  if (testDNExists(web)){
    next
  }
  tbls_AllAge[[i]] <- list()
  tbls_AllAge[[i]] <- web %>% 
    html_table(fill = T) # list of each table on pg (18) 

  headers <- web %>% 
    html_nodes("h3") %>%
    html_text()

  headers <- unname(sapply(headers, tidyHeader))

  # add column with event name (elements in headers[-1])
  tbls_AllAge[[i]] <- mapply(cbind, tbls_AllAge[[i]], 
                             "Event"=headers[-1], SIMPLIFY=F)
  tbls_AllAge[[i]] <- mapply(cbind, tbls_AllAge[[i]], 
                             "Year"=headers[-1], SIMPLIFY=F)
#########****  want to name it headers[1] and put into a list. 
  tbls_df <- do.call(rbind.data.frame, 
                     tbls_AllAge[[i]]) #makes df of all tables for 1 age gp 
  tbls_AllAge[[i]] <- tbls_df

}



```


##ALL  years (all ages)

```{r}
## 2 years  - so will have men all ages year 2019 

tbls_AllYear <- list()
#tbls_AllYear <- lapply(1:2, function(x){ list()})
for( year in Year ){
  index = year - 1970  #***
  
  for (i in AgeGpID) {
    path <- sprintf("https://www.usms.org/comp/tt/toptenlist.php?CourseID=1&Year=%d&Sex=M&AgeGroupID=%d", year, i )
    web <- read_html(path)
     if (testDNExists(web)){
      next
    }
    tbls_AllAge[[i]] <- list()
    tbls_AllAge[[i]] <- web %>% 
      html_table(fill = T) # list of each table on pg (18) 

    headers <- web %>% 
      html_nodes("h3") %>%
      html_text()

    headers <- unname(sapply(headers, tidyHeader))

    # add column with event name (elements in headers[-1])
    tbls_AllAge[[i]] <- mapply(cbind, tbls_AllAge[[i]], 
                             "Event"=headers[-1], SIMPLIFY=F)

    #########****  want to name it headers[1] and put into a list. 
    tbls_df <- do.call(rbind.data.frame, 
                     tbls_AllAge[[i]]) #makes df of all tables for 1 age gp 
    tbls_AllAge[[i]] <- tbls_df

    }
  tbls_AllAge_df <- do.call(rbind.data.frame, tbls_AllAge)
  tbls_AllAge_df <- cbind(tbls_AllAge_df, 
                        "Year" = rep(paste(year), nrow(tbls_AllAge_df)))
  tbls_AllYear[[index]] <- tbls_AllAge_df
}


```




##ALL  Sexes (all years, all ages)

```{r}
## 2 years to test, both sexes

tbls_AllSex <- list()
sexIndex <- 0
for (sex in Sex){
  sexIndex <- sexIndex + 1
  tbls_AllYear <- list()

  for( year in c(2018:2019)){
    index = year - 2017  #***
  
    for (i in AgeGpID) {
      path <- sprintf("https://www.usms.org/comp/tt/toptenlist.php?CourseID=1&Year=%d&Sex=M&AgeGroupID=%d", year, i )
      web <- read_html(path)
      if (testDNExists(web)){
        next
      }
      tbls_AllAge[[i]] <- list()
      tbls_AllAge[[i]] <- web %>% 
        html_table(fill = T) # list of each table on pg (18) 

      headers <- web %>% 
        html_nodes("h3") %>%
        html_text()

      headers <- unname(sapply(headers, tidyHeader))

    # add column with event name (elements in headers[-1])
      tbls_AllAge[[i]] <- mapply(cbind, tbls_AllAge[[i]], 
                             "Event"=headers[-1], SIMPLIFY=F)

    #########****  want to name it headers[1] and put into a list. 
      tbls_df <- do.call(rbind.data.frame, 
                     tbls_AllAge[[i]]) #makes df of all tables for 1 age gp 
      tbls_AllAge[[i]] <- tbls_df

      }
    tbls_AllAge_df <- do.call(rbind.data.frame, tbls_AllAge)
    tbls_AllAge_df <- cbind(tbls_AllAge_df, 
                        "Year" = rep(paste(year), nrow(tbls_AllAge_df)))
    tbls_AllYear[[index]] <- tbls_AllAge_df
  }

  tbls_AllYear_df <- do.call(rbind.data.frame, tbls_AllYear)
  tbls_AllYear_df <- cbind(tbls_AllYear_df, 
                        "Sex" = rep(paste(sex), nrow(tbls_AllYear_df)))
  tbls_AllSex[[sexIndex]] <- tbls_AllYear_df
  
}
```
